CREATE TABLE `employee` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOGINID` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
